project:
  type: website
  output-dir: docs
  render:
    - /template.qmd
  resources:
    - /*.jpg

website:
  title: "Quarto Clean Format"
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/Rahuketu86/quarto-simpleclean-revealjs

format:
  html:
    toc: true